use_frameworks!

platform :ios, '9.0'

target 'PlayerSocket_Example' do
  pod 'PlayerSocket', :path => '../'
  pod 'Socket.IO-Client-Swift', '~> 14.0.0' 
  pod 'lottie-ios' # https://github.com/airbnb/lottie-ios

  target 'PlayerSocket_Tests' do
    inherit! :search_paths
  end
end
